#!/usr/bin/env bash
# The landing pages are full parallel copies with no shared template — every
# structural edit must land in every language. This compares the
# structure-bearing skeleton of each page (element ids, /media/ video sources
# and posters, CSS class definitions) against English and fails on drift.
# Copy (translated text) is free to differ; structure is not.
#
# Generic over N languages: every website/<code>/index.html is discovered, so
# adding a language needs no edit here. With two pages this was a nicety; with
# seven it is the only thing standing between a copy edit and a page that
# silently loses a section.
set -euo pipefail

EN=website/index.html

skeleton() {
  {
    grep -o 'id="[^"]*"' "$1" || true
    # Localized app screenshots (/media/app/<code>/…) are the one sanctioned
    # per-language asset divergence — normalize the prefix so each language may
    # point at its own set while the FILENAMES still must match the EN page.
    grep -o 'src="/media/[^"]*"' "$1" | sed -E 's|/media/app/[a-z]{2}/|/media/app/|' || true
    grep -o 'poster="/media/[^"]*"' "$1" || true
    grep -oE '^[[:space:]]*\.[a-z][a-zA-Z0-9., :()-]*\{' "$1" | sed 's/[[:space:]]//g' || true
  } | sort
}

# Two-letter directories only. website/ also holds privacy/, terms/, refund/
# and oauth-native/ — separate pages, not translations of the landing, and
# comparing them against it would fail on every run.
langs=()
for dir in website/*/; do
  code="$(basename "$dir")"
  [[ "$code" =~ ^[a-z]{2}$ ]] || continue
  [ -f "${dir}index.html" ] || continue
  langs+=("$code")
done

if [ ${#langs[@]} -eq 0 ]; then
  echo "::error::no website/<code>/index.html found — did the landings move?"
  exit 1
fi

failed=0
for code in "${langs[@]}"; do
  page="website/${code}/index.html"
  if ! diff <(skeleton "$EN") <(skeleton "$page") > "/tmp/lockstep-${code}.diff"; then
    echo "::error::website EN/${code} structural drift — edit every landing in lockstep (< only in EN, > only in ${code}):"
    cat "/tmp/lockstep-${code}.diff"
    failed=1
  fi
done

[ "$failed" -eq 0 ] || exit 1

# A language is only "shipped" once search engines can see it. Adding the
# directory but forgetting the hreflang set or the sitemap entry leaves the page
# live and unreachable, which looks identical to done from the browser.
all=(en "${langs[@]}")
for code in "${all[@]}"; do
  [ "$code" = en ] && page="$EN" || page="website/${code}/index.html"
  [ "$code" = en ] && href="/" || href="/${code}/"

  grep -q "<html lang=\"${code}\">" "$page" || {
    echo "::error::${page} does not declare <html lang=\"${code}\">"; failed=1; }

  # Every page must point at every other one, or the set reads as unrelated
  # pages rather than translations of one another.
  for other in "${all[@]}" x-default; do
    grep -q "hreflang=\"${other}\"" "$page" || {
      echo "::error::${page} is missing hreflang=\"${other}\""; failed=1; }
  done

  grep -q "<loc>https://klorn.ai${href}</loc>" website/sitemap.xml || {
    echo "::error::website/sitemap.xml has no entry for ${href}"; failed=1; }

  # The language switcher must mark THIS page's language as current, in the nav
  # menu and the footer both. Pages are generated by copying the English body,
  # where the marker sits on English — a screen reader on the Japanese page
  # would otherwise be told it is reading English.
  marked="$(grep -o 'data-lang-pick="[a-z]\{2\}"[^>]*aria-current="true"' "$page" \
            | grep -o 'data-lang-pick="[a-z]\{2\}"' | sort -u | tr -d '\n')"
  [ "$marked" = "data-lang-pick=\"${code}\"" ] || {
    echo "::error::${page} marks aria-current on [${marked:-none}], expected only ${code}"
    failed=1; }
done

[ "$failed" -eq 0 ] || exit 1

echo "EN skeleton matches ${#langs[@]} translated landing(s) [${langs[*]}] ($(skeleton "$EN" | wc -l | tr -d ' ') anchors)."
echo "hreflang + sitemap complete for ${#all[@]} language(s) [${all[*]}]."
