name: prettier
on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - biome.json
      - package.json
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - name: Format Check
        run: biome format packages/
